{% set version = "3.1.4" %}

package:
  name: openpyxl
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/o/openpyxl/openpyxl-{{ version }}.tar.gz
  sha256: 8d2c8adf5d20d6ce8f9bca381df86b534835e974ed0156dacefa76f68c1d69fb

build:
  number: 0
  skip: True  # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --global-option="--with-cython" -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - cython
    - pip
    - setuptools
    - wheel
  run:
    - python
    - et_xmlfile

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - openpyxl
    - openpyxl.cell
    - openpyxl.chart
    - openpyxl.chartsheet
    - openpyxl.comments
    - openpyxl.compat
    - openpyxl.descriptors
    - openpyxl.drawing
    - openpyxl.formatting
    - openpyxl.formula
    - openpyxl.packaging
    - openpyxl.pivot
    - openpyxl.reader
    - openpyxl.styles
    - openpyxl.utils
    - openpyxl.workbook
    - openpyxl.workbook.external_link
    - openpyxl.worksheet
    - openpyxl.writer
    - openpyxl.xml

about:
  home: https://openpyxl.readthedocs.io
  license: MIT
  license_family: MIT
  license_file: LICENCE.rst
  summary: A Python library to read/write Excel 2010 xlsx/xlsm files
  description: |
    openpyxl is a Python library to read/write Excel 2010
    xlsx/xlsm/xltx/xltm files.
  doc_url: https://openpyxl.readthedocs.io/
  dev_url: https://foss.heptapod.net/openpyxl/openpyxl

extra:
  recipe-maintainers:
    - curtisalexander
    - ocefpaf
