travis:
  secure:
    BINSTAR_TOKEN: VLSl0ODcG1EVCfXbkGJ+1fktstmA9fyPiBxj1fksjZoLAw0XfJ2xBcEZOLjNOBuwf4+7bSsW0RhdMMBElURmIuGm+uc0LLNzWYo9uS/mdJE7CO+yU+BcOPsdY1V1fLFkP+BR7ICx65aYMRmI9WC3na40G/VXmTneOn2H7/WQnb+XG/R2sU16GNLAvnkyGBzuacsTTO+MPJAAdPuyLlHej22D485uwAunFdy18pBEcTh0cgaRorHbn4m1qsroNibg2UbDnLxiV+8uONdy2EJNg0CsAMLmWDL7RZRgtYkl44b2MhczoUvlIFqMeFeIaI9/JvkvTLk8Xek1lfBzPBHbFZ+EBMDb4oj8q9l4rbcieDIl90+xDpEBm/5LWP3WFGd58ZIm43Lt/gQ6VSaLh8LLVFqp2JzRqDt2jYOwr9QKPkmozw95wlExpF7DpdQp9sDglC5/mSsSEog50bB8hu23mdQ52vLYlbHCTi6HO0qznMCNCswhm4fZojuUFYELSQAwrsDrbggK33ryNE/wHV8Ng9SJAcKbBIvid4jRfF0LqCfR7b+iUDAtmHpVyNzavqFOsOYIRGj7dw5c1aSQyfF8TvwSTRRZKgkL4h+QV6VTh1EDaQwS3jvIO44z5TIOxy0eKHG7rlZ3Thlmv/BX/I3/PwzUnKqZED5lbzuvvLxPaY4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
