travis:
  secure:
    BINSTAR_TOKEN: ThkG7nAPn86Or1IgJcJOvxu9CvYsuMI7DjLNYHkYmwKDm2c1u4+F8K2gnEu2S/RgpLPDmSt1NmTIEVhTLxLaJDJsW678LjCY/bdya6eyKksFwiNAEOBvTEJdxMDzzyTqQUhYg51ABeFWbJPMDxmc22QJ3LxxjwPwhNdxEIbYAQR2KZIkMzLGCTNHWGS3Pg0ym6n7UfiDfDG14CeNK2OJNRhsW9yt/TpiCG1ivXl13NkvgvK6m9RpEXq1Lsq562ABlAgjLm6Qg2OjKhNKPDXAEywZ65USSfG5lQ9ZPkfQ1fTJEfVJ93I4xbRHTsojk1wyJptH3wf7uej9HPiaDGrxlhH5Mk5IGLeirbzWfv4q1I/n7EjQsVEtExh73SXOfM1AksNzM0aBjO0jg80a/L0fxcY3CmLkq0GmReDbAN+b8nKVSIRtOOX/FE3zq5by+D+bzVMk7e5doKkdDF7+lkARQ/w3ZiEJDm6i+RjQKzIvgAuJZ61gJghpxD6aqcoJlIMFK/95JVc3rZE1du4cTYGsGLdGRcJTp66wFzIuuOFz4Tpt+q9u/hsm5OmkZfVG/FM/vOQtpgZHGEmqp2T2P4KYaf+m2anrOoEMIlObvwlMd01axJKgdMwyd+eDSYld5k1aTqb9kpRgKculNBhoeYGNMSMMv8TdApL3OL5ahZebvAA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
